/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;
import java.util.ArrayList;
import net.objecthunter.exp4j.Expression;
import net.objecthunter.exp4j.ExpressionBuilder;
import net.objecthunter.exp4j.operator.Operator;
import javax.swing.Timer;

public class frameCalculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameCalculadora.class.getName());
    
    
    
    Operator porcentagem = new Operator("%", 1, true, Operator.PRECEDENCE_UNARY_MINUS) {
    @Override
    public double apply(double... args) {
        return args[0] / 100;
    }
};
    
    
    /**
     * Creates new form frameCalculadora
     */
    public frameCalculadora() {
        initComponents();
    }
    ArrayList <String> numeros = new ArrayList<>();
    ArrayList <Character> sinais = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResultado = new javax.swing.JLabel();
        btnZero = new javax.swing.JButton();
        btnPonto = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnSinalIgual = new javax.swing.JButton();
        btnOito = new javax.swing.JButton();
        btnSete = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnSinalAdicao = new javax.swing.JButton();
        btnQuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnUm = new javax.swing.JButton();
        btnDois = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnSinalSubtracao = new javax.swing.JButton();
        btnSinalMultiplicacao = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnParenteses = new javax.swing.JButton();
        btnPorcentagem = new javax.swing.JButton();
        btnDivisao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblResultado.setBackground(new java.awt.Color(153, 153, 153));
        lblResultado.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResultado.setToolTipText("");
        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnZero.setText("0");
        btnZero.addActionListener(this::btnZeroActionPerformed);

        btnPonto.setText(".");
        btnPonto.addActionListener(this::btnPontoActionPerformed);

        btnDeletar.setText("Del");
        btnDeletar.addActionListener(this::btnDeletarActionPerformed);

        btnSinalIgual.setBackground(new java.awt.Color(204, 226, 236));
        btnSinalIgual.setText("=");
        btnSinalIgual.addActionListener(this::btnSinalIgualActionPerformed);

        btnOito.setText("8");
        btnOito.addActionListener(this::btnOitoActionPerformed);

        btnSete.setText("7");
        btnSete.addActionListener(this::btnSeteActionPerformed);

        btn9.setText("9");
        btn9.addActionListener(this::btn9ActionPerformed);

        btnSinalAdicao.setBackground(new java.awt.Color(204, 226, 236));
        btnSinalAdicao.setText("+");
        btnSinalAdicao.addActionListener(this::btnSinalAdicaoActionPerformed);

        btnQuatro.setText("4");
        btnQuatro.addActionListener(this::btnQuatroActionPerformed);

        btnCinco.setText("5");
        btnCinco.addActionListener(this::btnCincoActionPerformed);

        btnSeis.setText("6");
        btnSeis.addActionListener(this::btnSeisActionPerformed);

        btnUm.setText("1");
        btnUm.addActionListener(this::btnUmActionPerformed);

        btnDois.setText("2");
        btnDois.addActionListener(this::btnDoisActionPerformed);

        btnTres.setText("3");
        btnTres.addActionListener(this::btnTresActionPerformed);

        btnSinalSubtracao.setBackground(new java.awt.Color(204, 226, 236));
        btnSinalSubtracao.setText("-");
        btnSinalSubtracao.addActionListener(this::btnSinalSubtracaoActionPerformed);

        btnSinalMultiplicacao.setBackground(new java.awt.Color(204, 226, 236));
        btnSinalMultiplicacao.setText("x");
        btnSinalMultiplicacao.addActionListener(this::btnSinalMultiplicacaoActionPerformed);

        btnClear.setBackground(new java.awt.Color(204, 226, 236));
        btnClear.setText("AC");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnParenteses.setBackground(new java.awt.Color(204, 226, 236));
        btnParenteses.setText("( )");
        btnParenteses.addActionListener(this::btnParentesesActionPerformed);

        btnPorcentagem.setBackground(new java.awt.Color(204, 226, 236));
        btnPorcentagem.setText("%");
        btnPorcentagem.addActionListener(this::btnPorcentagemActionPerformed);

        btnDivisao.setBackground(new java.awt.Color(204, 226, 236));
        btnDivisao.setText("/");
        btnDivisao.addActionListener(this::btnDivisaoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTres, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSete, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(btnZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnParenteses, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPorcentagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSinalIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSinalAdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSinalSubtracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSinalMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnParenteses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPorcentagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUm, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnDois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSinalMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSinalSubtracao, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnQuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSinalAdicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinalIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
       String textoAtual = lblResultado.getText();
       textoAtual += "0";
       lblResultado.setText(textoAtual);    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPontoActionPerformed
       String textoAtual = lblResultado.getText();
       textoAtual += ".";
       lblResultado.setText(textoAtual);    }//GEN-LAST:event_btnPontoActionPerformed

    private void btnSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeteActionPerformed
       String textoAtual = lblResultado.getText();
       textoAtual += "7";
       lblResultado.setText(textoAtual);    }//GEN-LAST:event_btnSeteActionPerformed

    private void btnUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmActionPerformed
       String textoAtual = lblResultado.getText();
       textoAtual += "1";
       lblResultado.setText(textoAtual);
    }//GEN-LAST:event_btnUmActionPerformed

    private void btnDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoisActionPerformed
       String textoAtual = lblResultado.getText();
       textoAtual += "2";
       lblResultado.setText(textoAtual);    }//GEN-LAST:event_btnDoisActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
       String textoAtual = lblResultado.getText();
       textoAtual += "3";
       lblResultado.setText(textoAtual);
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuatroActionPerformed
       String textoAtual = lblResultado.getText();
       textoAtual += "4";
       lblResultado.setText(textoAtual);
    }//GEN-LAST:event_btnQuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
       String textoAtual = lblResultado.getText();
       textoAtual += "5";
       lblResultado.setText(textoAtual);
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
       String textoAtual = lblResultado.getText();
       textoAtual += "6";
       lblResultado.setText(textoAtual);    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOitoActionPerformed
       String textoAtual = lblResultado.getText();
       textoAtual += "8";
       lblResultado.setText(textoAtual);    }//GEN-LAST:event_btnOitoActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
       String textoAtual = lblResultado.getText();
       textoAtual += "9";
       lblResultado.setText(textoAtual);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
       String textoAtual = lblResultado.getText();
       if (textoAtual != null && !textoAtual.isEmpty()) {
            //Utilizo o substring para coletar uma parte da string, ou seja, pego do inicio da string ate o penultimo caractere dela
            lblResultado.setText(textoAtual.substring(0, textoAtual.length()-1));
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        lblResultado.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSinalAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinalAdicaoActionPerformed
        String textoAtual = lblResultado.getText();
        textoAtual += "+";
        lblResultado.setText(textoAtual);
        
    }//GEN-LAST:event_btnSinalAdicaoActionPerformed

    private void btnSinalIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinalIgualActionPerformed
        String textoAtual = lblResultado.getText();
        boolean erro = false;
        try{
        Expression e = new ExpressionBuilder(textoAtual).operator(porcentagem).build();
        String resultado = Double.toString(e.evaluate());
        lblResultado.setText(resultado);
        
        }
        catch(Exception e){
            lblResultado.setText("Erro, Expressão Invalida");
            javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener(){
                @Override
                public void actionPerformed(java.awt.event.ActionEvent e){
                    lblResultado.setText("");
                }
            });
        timer.setRepeats(false);
        timer.start();
        }
        
    }//GEN-LAST:event_btnSinalIgualActionPerformed

    private void btnSinalSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinalSubtracaoActionPerformed
        String textoAtual = lblResultado.getText();
        textoAtual += "-";
        lblResultado.setText(textoAtual);    }//GEN-LAST:event_btnSinalSubtracaoActionPerformed

    private void btnSinalMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinalMultiplicacaoActionPerformed
        String textoAtual = lblResultado.getText();
        textoAtual += "*";
        lblResultado.setText(textoAtual);    }//GEN-LAST:event_btnSinalMultiplicacaoActionPerformed

    private void btnDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisaoActionPerformed
        String textoAtual = lblResultado.getText();
        textoAtual += "/";
        lblResultado.setText(textoAtual);    }//GEN-LAST:event_btnDivisaoActionPerformed

    private void btnParentesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentesesActionPerformed
        boolean temParentesesAntes= false;
        String textoAtual = lblResultado.getText();
        int tamanhoString = textoAtual.length();
        
        //aqui ele ira vericar a partir do final da string se há um parenteses aberto antes, se tiver ele registra no booleano, colocando como true
        //caso ele encongtre um final de parenteses ele sai do loop sem verificar o que vem antes, pois poderia quebrar o codigo e a ooperação -> exemplo 2 + ( 2 + 2 ) )
        for(int i = tamanhoString-1; i>=0; i--){
            if(textoAtual.charAt(i) == '('){
                temParentesesAntes = true;
                break;
            }
            else if(textoAtual.charAt(i) == ')'){
                break;
            }
        }
        
        if(temParentesesAntes == true){
            textoAtual += ")";
        }
        else{
            textoAtual += "(";
        }
        
        lblResultado.setText(textoAtual);    }//GEN-LAST:event_btnParentesesActionPerformed

    private void btnPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentagemActionPerformed
        String textoAtual = lblResultado.getText();
       textoAtual += "%";
       lblResultado.setText(textoAtual);    }//GEN-LAST:event_btnPorcentagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameCalculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnDivisao;
    private javax.swing.JButton btnDois;
    private javax.swing.JButton btnOito;
    private javax.swing.JButton btnParenteses;
    private javax.swing.JButton btnPonto;
    private javax.swing.JButton btnPorcentagem;
    private javax.swing.JButton btnQuatro;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSete;
    private javax.swing.JButton btnSinalAdicao;
    private javax.swing.JButton btnSinalIgual;
    private javax.swing.JButton btnSinalMultiplicacao;
    private javax.swing.JButton btnSinalSubtracao;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUm;
    private javax.swing.JButton btnZero;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
